package com.controller;

public enum Event
{
    ADD_EXPENSE,
    DELETE_EXPENSE,
    MAIN_FORM_CLOSE,
    MAIN_FORM_SHOW,
    MAIN_FORM_HIDE,
    EXPENSE_FORM_CLOSE,
    EXPENSE_FORM_SHOW,
    EXPENSE_FORM_HIDE,
    UPDATE_TEST_TEXT_FIELD
}
